export const data = [
    {
        alias: "total-wine-and-more-plano-3",
        categories: [[Object], [Object]],
        coordinates: { latitude: 33.010399, longitude: -96.7097064 },
        delivery_time: 38,
        display_phone: "(972) 943-0767",
        distance: 5406.922567581389,
        id: "0yPlE6RWV6mw4XecxKr78A",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/HPvZSlIWgUjRgQcYe8BkCA/o.jpg",
        is_closed: false,
        location: {
            address1: "721 N Central Expy",
            address2: "Ste 200",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75075",
        },
        name: "Total Wine & More",
        phone: "+19729430767",
        price: "$$",
        rating: 3.5,
        review_count: 104,
        transactions: [],
        url: "https://www.yelp.com/biz/total-wine-and-more-plano-3?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "richardson-beer-and-wine-richardson",
        categories: [[Object]],
        coordinates: { latitude: 32.976203, longitude: -96.737256 },
        delivery_time: 38,
        display_phone: "(972) 680-7912",
        distance: 4478.4134281165025,
        id: "oVpo-y-t5nsjSGOaYoDRQw",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/XeXFPhkhpjxMuPRcdpuQOQ/o.jpg",
        is_closed: false,
        location: {
            address1: "515 W Campbell Rd",
            address2: "Ste 105",
            address3: null,
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75080",
        },
        name: "Richardson Beer & Wine",
        phone: "+19726807912",
        price: "$",
        rating: 4,
        review_count: 7,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/richardson-beer-and-wine-richardson?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-plano",
        categories: [[Object]],
        coordinates: {
            latitude: 33.041319226059,
            longitude: -96.7001149432301,
        },
        delivery_time: 38,
        display_phone: "(972) 423-6688",
        distance: 8606.00422370109,
        id: "Q7YQ-NTmmnBPDYxKfRqZmA",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/3B8HozlsIawMsMiA65R_Qw/o.jpg",
        is_closed: false,
        location: {
            address1: "3404 N Central Expy",
            address2: "",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75074",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+19724236688",
        price: "$$",
        rating: 4,
        review_count: 31,
        transactions: [],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-plano-3",
        categories: [[Object]],
        coordinates: { latitude: 33.02703, longitude: -96.82682 },
        delivery_time: 38,
        display_phone: "(972) 250-0500",
        distance: 14431.225756026663,
        id: "yqhYB5Q5x6x5ZKeDQM9SCw",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/3CKh9eCJCJDV8NiMRLV4HA/o.jpg",
        is_closed: false,
        location: {
            address1: "5930 W Park Blvd",
            address2: "",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75093",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+19722500500",
        price: "$$",
        rating: 3.5,
        review_count: 64,
        transactions: [],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-plano-3?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "7-eleven-richardson-2",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 32.9749395086055,
            longitude: -96.7147297790985,
        },
        delivery_time: 38,
        display_phone: "(972) 231-9945",
        distance: 2481.8526399192715,
        id: "3RFWSKjyTYwbTlCnLSNH-w",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/CvcE6mRquI2f6E7B3CdYtw/o.jpg",
        is_closed: false,
        location: {
            address1: "700 E Campbell Rd",
            address2: "",
            address3: "",
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75081",
        },
        name: "7-Eleven",
        phone: "+19722319945",
        price: "$",
        rating: 4.5,
        review_count: 15,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/7-eleven-richardson-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "the-liquor-outpost-allen",
        categories: [[Object]],
        coordinates: { latitude: 33.130396, longitude: -96.675659 },
        delivery_time: 38,
        display_phone: "(972) 649-6513",
        distance: 18529.95110919182,
        id: "rh3B3_0vLjgABmRvSHim8w",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/ZT0idT8Zy82E6zBPf9GQLw/o.jpg",
        is_closed: false,
        location: {
            address1: "950 W Stacy Rd",
            address2: "",
            address3: null,
            city: "Allen",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75013",
        },
        name: "The Liquor Outpost",
        phone: "+19726496513",
        price: "$",
        rating: 2,
        review_count: 17,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/the-liquor-outpost-allen?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "goody-goody-liquor-addison",
        categories: [[Object]],
        coordinates: {
            latitude: 32.9509925842285,
            longitude: -96.8309936523438,
        },
        delivery_time: 38,
        display_phone: "(214) 765-6874",
        distance: 13127.656208911456,
        id: "eUuAZg180ewAFkf3lMZKGQ",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/_wYFoyQXj7dp9uONPPM4UA/o.jpg",
        is_closed: false,
        location: {
            address1: "14851 Inwood Rd",
            address2: "",
            address3: "",
            city: "Addison",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75001",
        },
        name: "Goody Goody Liquor",
        phone: "+12147656874",
        price: "$$",
        rating: 4,
        review_count: 38,
        transactions: [],
        url: "https://www.yelp.com/biz/goody-goody-liquor-addison?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "top-liquor-beer-and-wine-dallas-2",
        categories: [[Object]],
        coordinates: { latitude: 32.88691, longitude: -96.75704 },
        delivery_time: 38,
        display_phone: "(214) 377-8231",
        distance: 10560.162744936732,
        id: "3P4LzmKcIoI-5a8gBiDMNQ",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/9ZecXg4lYQ2S7k9-r_nnBQ/o.jpg",
        is_closed: false,
        location: {
            address1: "7606 Greenville Ave",
            address2: null,
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75231",
        },
        name: "Top Liquor Beer And Wine",
        phone: "+12143778231",
        price: "$",
        rating: 3.5,
        review_count: 11,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/top-liquor-beer-and-wine-dallas-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "lockwood-distilling-richardson",
        categories: [[Object]],
        coordinates: { latitude: 32.952426, longitude: -96.736164 },
        delivery_time: 38,
        display_phone: "(469) 399-1599",
        distance: 4385.666741913694,
        id: "2EQH5eQCKBLc8gd0qIWZ_g",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/8_kAuAP9f5FCwjrqNfOtTQ/o.jpg",
        is_closed: false,
        location: {
            address1: "506 Lockwood Dr",
            address2: "Ste A",
            address3: null,
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75080",
        },
        name: "Lockwood Distilling",
        phone: "+14693991599",
        price: "$$",
        rating: 4.5,
        review_count: 124,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/lockwood-distilling-richardson?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-dallas-2",
        categories: [[Object]],
        coordinates: { latitude: 32.878684, longitude: -96.768971 },
        delivery_time: 38,
        display_phone: "(214) 369-2800",
        distance: 11960.33904416997,
        id: "Ryj5-UYz4ODqmOZ2p5rrxw",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/Oe4Jln0uxoS5aUo_j9C-fA/o.jpg",
        is_closed: false,
        location: {
            address1: "9500 N Central Expy",
            address2: "Ste 200",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75231",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+12143692800",
        price: "$$",
        rating: 4,
        review_count: 154,
        transactions: [],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-dallas-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-plano-2",
        categories: [[Object]],
        coordinates: {
            latitude: 33.018529922729,
            longitude: -96.7674399912357,
        },
        delivery_time: 38,
        display_phone: "(972) 867-2821",
        distance: 9313.732409674963,
        id: "Tycojb09QlIBVurywjsang",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/cWEQevcR-mqhxFLkxe4OFA/o.jpg",
        is_closed: false,
        location: {
            address1: "1453 Coit Rd",
            address2: "",
            address3: null,
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75075",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+19728672821",
        price: "$$",
        rating: 4,
        review_count: 16,
        transactions: [],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-plano-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "lone-star-beverages-carrollton",
        categories: [[Object], [Object]],
        coordinates: { latitude: 32.998913, longitude: -96.887179 },
        delivery_time: 38,
        display_phone: "(972) 395-0240",
        distance: 18666.75332225391,
        id: "iGjYD7eP0XKPc2_lzbR2Ew",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/Mk9XlcRNBBoHdltIf4bQhQ/o.jpg",
        is_closed: false,
        location: {
            address1: "3065 N Josey Ln",
            address2: "Ste 62",
            address3: "",
            city: "Carrollton",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75007",
        },
        name: "Lone Star Beverages",
        phone: "+19723950240",
        price: "$$",
        rating: 4.5,
        review_count: 80,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/lone-star-beverages-carrollton?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "total-wine-and-more-plano-2",
        categories: [[Object], [Object]],
        coordinates: {
            latitude: 33.0971964683318,
            longitude: -96.8013255337295,
        },
        delivery_time: 38,
        display_phone: "(214) 436-5518",
        distance: 17987.523474463433,
        id: "62FW-M4pEFidxLcnHRzPzQ",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/rAPToygScPRLokfXqS5drw/o.jpg",
        is_closed: false,
        location: {
            address1: "8700 Preston Rd",
            address2: "Ste 113",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75024",
        },
        name: "Total Wine & More",
        phone: "+12144365518",
        price: "$$",
        rating: 4,
        review_count: 135,
        transactions: [],
        url: "https://www.yelp.com/biz/total-wine-and-more-plano-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "omg-tacos-richardson-2",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 32.9430692, longitude: -96.7426709 },
        delivery_time: 38,
        display_phone: "(469) 941-4317",
        distance: 5378.549415653156,
        id: "6aycQ6G41o_b-7SMSPoEYg",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/sKm_cfeJ16YrjLUcOsUevQ/o.jpg",
        is_closed: false,
        location: {
            address1: "744 S Central Expy",
            address2: "",
            address3: null,
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75080",
        },
        name: "OMG Tacos",
        phone: "+14699414317",
        price: "$",
        rating: 4,
        review_count: 274,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/omg-tacos-richardson-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-sachse-6",
        categories: [[Object]],
        coordinates: { latitude: 32.993002, longitude: -96.568047 },
        delivery_time: 38,
        display_phone: "(972) 429-4456",
        distance: 11937.85318263842,
        id: "Pjt4voGX3PUB1w4SOperlA",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/5AluzusJQXsHlnBrGCELFA/o.jpg",
        is_closed: false,
        location: {
            address1: "8110 Highway 78",
            address2: "",
            address3: null,
            city: "Sachse",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75048",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+19724294456",
        rating: 4,
        review_count: 7,
        transactions: [],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-sachse-6?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "goody-goody-liquor-rowlett",
        categories: [[Object]],
        coordinates: { latitude: 32.906168, longitude: -96.568445 },
        delivery_time: 38,
        display_phone: "(972) 581-1090",
        distance: 13165.373559730235,
        id: "tDAFOGk3q8Nw4tFBIUpOMg",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/xSittysQodLOoYJyc361xA/o.jpg",
        is_closed: false,
        location: {
            address1: "3500 Lakeview Pkwy",
            address2: "Ste 100",
            address3: "",
            city: "Rowlett",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75088",
        },
        name: "Goody Goody Liquor",
        phone: "+19725811090",
        price: "$$",
        rating: 4,
        review_count: 23,
        transactions: [],
        url: "https://www.yelp.com/biz/goody-goody-liquor-rowlett?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "north-italia-plano-2",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 33.08078062155034,
            longitude: -96.82643665639652,
        },
        delivery_time: 38,
        display_phone: "(214) 291-6996",
        distance: 18067.33699064082,
        id: "Wj71IYNYXPTeXiifvpJxhw",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/Rz5bZkV-5umF1G4WbxRK_g/o.jpg",
        is_closed: false,
        location: {
            address1: "7501 Windrose Ave",
            address2: "Ste D190",
            address3: null,
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75024",
        },
        name: "North Italia",
        phone: "+12142916996",
        price: "$$",
        rating: 4,
        review_count: 1024,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/north-italia-plano-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "kute-chill-corner-richardson",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 32.944849, longitude: -96.693541 },
        delivery_time: 38,
        display_phone: "(469) 250-7100",
        distance: 2170.990729449599,
        id: "lQN4xu1Pfoq7P_v6YFaK3g",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/Bhmc0ybKaN1URBwHDap-Uw/o.jpg",
        is_closed: false,
        location: {
            address1: "1610 E Belt Line Rd",
            address2: null,
            address3: "",
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75081",
        },
        name: "Kute Chill Corner",
        phone: "+14692507100",
        price: "$",
        rating: 4,
        review_count: 10,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/kute-chill-corner-richardson?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "jeng-chi-restaurant-richardson-2",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 32.9533416983721,
            longitude: -96.7277272637164,
        },
        delivery_time: 38,
        display_phone: "(972) 669-9094",
        distance: 3604.1287099186575,
        id: "yO90P2WzywNtvXrsqYcJuA",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/y6oA3dzUl9H4s7S-OtvXTA/o.jpg",
        is_closed: false,
        location: {
            address1: "400 N Greenville Ave",
            address2: "Ste 11",
            address3: "",
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75081",
        },
        name: "Jeng Chi Restaurant",
        phone: "+19726699094",
        price: "$$",
        rating: 4,
        review_count: 1554,
        transactions: ["pickup", "restaurant_reservation", "delivery"],
        url: "https://www.yelp.com/biz/jeng-chi-restaurant-richardson-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-addison",
        categories: [[Object]],
        coordinates: { latitude: 32.953697, longitude: -96.831231 },
        delivery_time: 38,
        display_phone: "(972) 239-5891",
        distance: 13102.674452625151,
        id: "dD-6Pw18L_occ1GeZ7NDsg",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/lmN5VqV59MtfDVNZXjhggQ/o.jpg",
        is_closed: false,
        location: {
            address1: "15055 Inwood Rd",
            address2: "",
            address3: "",
            city: "Addison",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75001",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+19722395891",
        price: "$$",
        rating: 4,
        review_count: 30,
        transactions: [],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-addison?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "plano-super-bowl-plano",
        categories: [[Object], [Object]],
        coordinates: { latitude: 33.03381, longitude: -96.7 },
        delivery_time: 38,
        display_phone: "(972) 881-0242",
        distance: 7785.244929163671,
        id: "BfIkT4zld81yEgDm58jKhg",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/JzI6CNYlco3b5-mzS9bT-w/o.jpg",
        is_closed: false,
        location: {
            address1: "2521 K Ave",
            address2: "",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75074",
        },
        name: "Plano Super Bowl",
        phone: "+19728810242",
        price: "$$",
        rating: 3.5,
        review_count: 158,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/plano-super-bowl-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "liquor-park-plano",
        categories: [[Object]],
        coordinates: {
            latitude: 33.02986136821125,
            longitude: -96.7708995757516,
        },
        delivery_time: 38,
        display_phone: "(972) 867-7600",
        distance: 10402.5288021619,
        id: "2ltyrfMUydS1nBai7CiFdQ",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/AlANnQxv-u1vL1S0Qi4Lfw/o.jpg",
        is_closed: false,
        location: {
            address1: "2001 Coit Rd",
            address2: "Ste 307",
            address3: null,
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75075",
        },
        name: "Liquor Park",
        phone: "+19728677600",
        price: "$$",
        rating: 3.5,
        review_count: 13,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/liquor-park-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "bjs-restaurant-and-brewhouse-plano",
        categories: [[Object], [Object]],
        coordinates: {
            latitude: 33.01741563743607,
            longitude: -96.70964219999999,
        },
        delivery_time: 38,
        display_phone: "(972) 424-4262",
        distance: 6150.311437829178,
        id: "5COFY8FDJHbu6KGKt2y5uA",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/mqI783DQ_kn8_zGMyLFdZg/o.jpg",
        is_closed: false,
        location: {
            address1: "1101 N Central Expy",
            address2: "",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75075",
        },
        name: "BJ's Restaurant & Brewhouse",
        phone: "+19724244262",
        price: "$$",
        rating: 3,
        review_count: 394,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/bjs-restaurant-and-brewhouse-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "the-royal-daiquiri-dallas",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 32.903517, longitude: -96.716161 },
        delivery_time: 38,
        display_phone: "(469) 941-4986",
        distance: 7152.242618434958,
        id: "mU59D69NRRARSUOf3RRipA",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/Ce3ZkUsikMN5OB5leEdA0Q/o.jpg",
        is_closed: false,
        location: {
            address1: "9203 Skillman St",
            address2: "Ste 114",
            address3: null,
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75243",
        },
        name: "The Royal Daiquiri",
        phone: "+14699414986",
        price: "$$",
        rating: 4.5,
        review_count: 25,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/the-royal-daiquiri-dallas?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "total-wine-and-more-dallas-7",
        categories: [[Object], [Object]],
        coordinates: { latitude: 32.87450594, longitude: -96.76827589 },
        delivery_time: 38,
        display_phone: "(214) 750-4605",
        distance: 12295.323088350427,
        id: "l8bkXvc-kv1X9zhyuwjSQQ",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/VcKsf1XKM1-je8V6KE4fcg/o.jpg",
        is_closed: false,
        location: {
            address1: "9350 N Central Expy",
            address2: "",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75231",
        },
        name: "Total Wine & More",
        phone: "+12147504605",
        price: "$$",
        rating: 4,
        review_count: 170,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/total-wine-and-more-dallas-7?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "kings-x-dallas",
        categories: [[Object]],
        coordinates: { latitude: 32.90952, longitude: -96.74366 },
        delivery_time: 38,
        display_phone: "(972) 234-9064",
        distance: 7804.644072975504,
        id: "Q9bhE7moA0q0wCfGQ3Q9qQ",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/rcT6UlpiKYciBvKXl8DRZQ/o.jpg",
        is_closed: false,
        location: {
            address1: "9191 Forest Ln",
            address2: "",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75243",
        },
        name: "King's X",
        phone: "+19722349064",
        price: "$",
        rating: 4,
        review_count: 23,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/kings-x-dallas?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "bankhead-brewing-rowlett",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 32.90267, longitude: -96.56569 },
        delivery_time: 38,
        display_phone: "(214) 440-2080",
        distance: 13596.226754562598,
        id: "xugcaFALHWSxnAJ2veKthg",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/UXPi-LzhLD1GPWIDm2hskw/o.jpg",
        is_closed: false,
        location: {
            address1: "3840 Main St",
            address2: null,
            address3: "",
            city: "Rowlett",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75088",
        },
        name: "Bankhead Brewing",
        phone: "+12144402080",
        price: "$$",
        rating: 4.5,
        review_count: 731,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/bankhead-brewing-rowlett?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "daqs-2-geaux-mesquite",
        categories: [[Object], [Object]],
        coordinates: { latitude: 32.79656, longitude: -96.65303 },
        delivery_time: 38,
        display_phone: "(214) 531-7727",
        distance: 18983.378388198504,
        id: "dsl_Tuwwv2W74L5aln69Xw",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/4YG19dn7b7fTb3lJA57o9A/o.jpg",
        is_closed: false,
        location: {
            address1: "3733 N Town East Blvd",
            address2: "Ste 200",
            address3: "",
            city: "Mesquite",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75150",
        },
        name: "Daqs 2 Geaux",
        phone: "+12145317727",
        price: "$",
        rating: 4.5,
        review_count: 18,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/daqs-2-geaux-mesquite?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "truck-yard-the-colony",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 33.06982, longitude: -96.85764 },
        delivery_time: 38,
        display_phone: "(469) 401-6764",
        distance: 19430.939592829218,
        id: "gDv6DNt9-KMdaRE6fyE2Kg",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/pVx_ECmz3ksU1VksXVFEfg/o.jpg",
        is_closed: false,
        location: {
            address1: "5959 Grove Ln",
            address2: "",
            address3: null,
            city: "The Colony",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75056",
        },
        name: "Truck Yard",
        phone: "+14694016764",
        price: "$$",
        rating: 4,
        review_count: 278,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/truck-yard-the-colony?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "uptown-liquors-dallas",
        categories: [[Object]],
        coordinates: {
            latitude: 32.8025344167295,
            longitude: -96.8001246864045,
        },
        delivery_time: 38,
        display_phone: "(469) 620-2111",
        distance: 20654.04822211902,
        id: "ikZmvNxzUZMr7CNcUrReXg",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/Wm5FpZgs97rkuB-ZBsSfUg/o.jpg",
        is_closed: false,
        location: {
            address1: "3128 McKinney Ave",
            address2: "Ste D",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75204",
        },
        name: "Uptown Liquors",
        phone: "+14696202111",
        price: "$$",
        rating: 4.5,
        review_count: 30,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/uptown-liquors-dallas?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "goody-goody-liquor-dallas-7",
        categories: [[Object]],
        coordinates: {
            latitude: 32.8102741974746,
            longitude: -96.806730285958,
        },
        delivery_time: 38,
        display_phone: "(214) 765-6878",
        distance: 20230.52934410168,
        id: "dDTpZ1qZc5XIXcxQf9KK-Q",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/8pyMY4S6ar3UOsG1k6_PMQ/o.jpg",
        is_closed: false,
        location: {
            address1: "3316 Oak Lawn Ave",
            address2: "",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75219",
        },
        name: "Goody Goody Liquor",
        phone: "+12147656878",
        price: "$$",
        rating: 4.5,
        review_count: 166,
        transactions: [],
        url: "https://www.yelp.com/biz/goody-goody-liquor-dallas-7?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "empire-liquor-allen-allen",
        categories: [[Object]],
        coordinates: { latitude: 33.10017, longitude: -96.69517 },
        delivery_time: 38,
        display_phone: "(972) 332-8511",
        distance: 15118.170034280523,
        id: "qJs6sD8tFuRIjxiUSvPQXw",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/GERHKuqNLtfs9ZNO8uy5Dg/o.jpg",
        is_closed: false,
        location: {
            address1: "1205 W Mcdermott Dr",
            address2: null,
            address3: "",
            city: "Allen",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75013",
        },
        name: "Empire Liquor Allen",
        phone: "+19723328511",
        price: "$",
        rating: 5,
        review_count: 16,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/empire-liquor-allen-allen?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "s-and-k-beverages-plano",
        categories: [[Object]],
        coordinates: {
            latitude: 33.057734778472,
            longitude: -96.6945499367706,
        },
        delivery_time: 38,
        display_phone: "(972) 517-2598",
        distance: 10396.773738003494,
        id: "sW5IyTe4jIOO_WW0Nb1WtQ",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/FgRrSdiULYLvtOE2pv_52w/o.jpg",
        is_closed: false,
        location: {
            address1: "101 W Spring Creek Pkwy",
            address2: "Ste 741",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75023",
        },
        name: "S & K Beverages",
        phone: "+19725172598",
        price: "$$",
        rating: 4,
        review_count: 22,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/s-and-k-beverages-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "yard-house-addison-2",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 32.9504214201936,
            longitude: -96.819912555156,
        },
        delivery_time: 38,
        display_phone: "(972) 716-4004",
        distance: 12092.503065875218,
        id: "7kxDKpXGU8aNVfEVyyuESA",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/K3hBAVqgWpYQ50UnASg4Gw/o.jpg",
        is_closed: false,
        location: {
            address1: "5100 Belt Line Rd",
            address2: "Ste 230",
            address3: null,
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75254",
        },
        name: "Yard House",
        phone: "+19727164004",
        price: "$$",
        rating: 4,
        review_count: 833,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/yard-house-addison-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "cidercade-dallas-dallas-3",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 32.80579131444462,
            longitude: -96.84579252297651,
        },
        delivery_time: 38,
        display_phone: "(214) 208-1922",
        distance: 22770.445436137645,
        id: "Y186sB-qHIgMcFTvjnqRdw",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/aAyU2anZhniXUmkMK0HNgg/o.jpg",
        is_closed: false,
        location: {
            address1: "2777 Irving Blvd",
            address2: "Ste 200",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75207",
        },
        name: "Cidercade Dallas",
        phone: "+12142081922",
        price: "$$",
        rating: 4.5,
        review_count: 443,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/cidercade-dallas-dallas-3?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "7-eleven-frisco-12",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 33.1021834, longitude: -96.8153967 },
        delivery_time: 38,
        display_phone: "(214) 387-0319",
        distance: 19205.683065278376,
        id: "3wa-lnIhYbwn4p02K6s-CA",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/D0Kj53aS98Xo4luNhpMlZQ/o.jpg",
        is_closed: false,
        location: {
            address1: "7950 Gaylord Pkwy",
            address2: "",
            address3: "",
            city: "Frisco",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75034",
        },
        name: "7-Eleven",
        phone: "+12143870319",
        price: "$",
        rating: 3.5,
        review_count: 12,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/7-eleven-frisco-12?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "tompson-liquor-plano",
        categories: [[Object]],
        coordinates: { latitude: 33.040702, longitude: -96.751024 },
        delivery_time: 38,
        display_phone: "(972) 599-0900",
        distance: 10157.833482293849,
        id: "VvCyaMpZvHqchYg-Bc10Tw",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/twJLJpZwc9r1hAgWFTGSwg/o.jpg",
        is_closed: false,
        location: {
            address1: "3100 Independence Pkwy",
            address2: "",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75075",
        },
        name: "Tompson Liquor",
        phone: "+19725990900",
        price: "$$",
        rating: 4,
        review_count: 12,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/tompson-liquor-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "quick-treat-plano",
        categories: [[Object], [Object]],
        coordinates: {
            latitude: 33.05978199999897,
            longitude: -96.73279601165581,
        },
        delivery_time: 38,
        display_phone: "(469) 305-0786",
        distance: 11301.106930492664,
        id: "FhFmVB7RsRvgrV_JHzh0JA",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/wU_9O5luQNixyw9DlQE3Qw/o.jpg",
        is_closed: false,
        location: {
            address1: "2011 W Spring Creek Pkwy",
            address2: "Ste 100",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75023",
        },
        name: "Quick Treat",
        phone: "+14693050786",
        price: "$$",
        rating: 4,
        review_count: 14,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/quick-treat-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "corner-stop-dallas",
        categories: [[Object], [Object], [Object]],
        coordinates: { latitude: 32.8166, longitude: -96.77048 },
        delivery_time: 38,
        display_phone: "(214) 823-7702",
        distance: 18015.749366503416,
        id: "af6kTYPpp3ekr54z7axoXg",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/DP6MK-GJWN6abkjzmXTRfw/o.jpg",
        is_closed: false,
        location: {
            address1: "2203 Greenville Ave",
            address2: "",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75206",
        },
        name: "Corner Stop",
        phone: "+12148237702",
        price: "$",
        rating: 4,
        review_count: 8,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/corner-stop-dallas?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "specs-wines-spirits-and-finer-foods-the-colony",
        categories: [[Object]],
        coordinates: { latitude: 33.0691703, longitude: -96.8839832 },
        delivery_time: 38,
        display_phone: "(214) 469-2113",
        distance: 21415.053135861806,
        id: "02GLj85_y7V937--zkSdiQ",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/iFkHCgDxDWOXAK28PdB8Ng/o.jpg",
        is_closed: false,
        location: {
            address1: "4901 TX-121",
            address2: "",
            address3: "",
            city: "The Colony",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75056",
        },
        name: "Spec's Wines, Spirits & Finer Foods",
        phone: "+12144692113",
        price: "$",
        rating: 4,
        review_count: 46,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/specs-wines-spirits-and-finer-foods-the-colony?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "bulla-gastrobar-plano-3",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 33.078487238128105,
            longitude: -96.82742524892132,
        },
        delivery_time: 38,
        display_phone: "(972) 805-4590",
        distance: 17950.49845404456,
        id: "7Kn8g-hm_V_6TUIDfF5IIA",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/WOiIAfrJmZIdt0x70iUGlw/o.jpg",
        is_closed: false,
        location: {
            address1: "6007 Legacy Dr",
            address2: "Ste 180",
            address3: null,
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75024",
        },
        name: "Bulla Gastrobar",
        phone: "+19728054590",
        price: "$$",
        rating: 4.5,
        review_count: 1056,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/bulla-gastrobar-plano-3?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "melones-sports-bar-richardson",
        categories: [[Object]],
        coordinates: { latitude: 32.94432, longitude: -96.69395 },
        delivery_time: 38,
        display_phone: "(214) 613-2008",
        distance: 2170.9907294498203,
        id: "beDcxszKBKeGUteFOp-snw",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/ilmcnhvvf1-8lHbXSpwpcA/o.jpg",
        is_closed: false,
        location: {
            address1: "1610 E Belt Line Rd",
            address2: "",
            address3: "",
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75081",
        },
        name: "Melones Sports Bar",
        phone: "+12146132008",
        price: "$$",
        rating: 2,
        review_count: 36,
        transactions: ["pickup", "delivery"],
        url: "https://www.yelp.com/biz/melones-sports-bar-richardson?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "legacy-hall-plano-3",
        categories: [[Object], [Object]],
        coordinates: { latitude: 33.083271, longitude: -96.8258046 },
        delivery_time: 38,
        display_phone: "(972) 846-4255",
        distance: 18226.221468085634,
        id: "rT1uBjftW4GAXJUS2GW3pA",
        image_url:
            "https://s3-media2.fl.yelpcdn.com/bphoto/8JZ6OC3oMGWSnrGBC7SkaA/o.jpg",
        is_closed: false,
        location: {
            address1: "7800 Windrose Ave",
            address2: "",
            address3: null,
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75024",
        },
        name: "Legacy Hall",
        phone: "+19728464255",
        price: "$$",
        rating: 4,
        review_count: 1179,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/legacy-hall-plano-3?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "goody-goody-liquor-the-colony",
        categories: [[Object]],
        coordinates: { latitude: 33.07158, longitude: -96.87881 },
        delivery_time: 38,
        display_phone: "(214) 765-6875",
        distance: 21162.94486774957,
        id: "kIEeC-ZTxAtkcY-P2H07wA",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/KFUBLEEGdyJXDxHXu-_3PQ/o.jpg",
        is_closed: false,
        location: {
            address1: "5285 State Hwy 121",
            address2: "",
            address3: "",
            city: "The Colony",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75056",
        },
        name: "Goody Goody Liquor",
        phone: "+12147656875",
        price: "$$",
        rating: 4,
        review_count: 41,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/goody-goody-liquor-the-colony?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "tight-ends-sports-bar-and-grill-plano",
        categories: [[Object]],
        coordinates: { latitude: 33.092629, longitude: -96.8130363 },
        delivery_time: 38,
        display_phone: "(469) 850-6796",
        distance: 18231.212718132338,
        id: "6ZtPB01PPjt5nv75K_R6LA",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/IKghZoue_6HYzKolaylTXw/o.jpg",
        is_closed: false,
        location: {
            address1: "5584 State Hwy 121",
            address2: "",
            address3: null,
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75024",
        },
        name: "Tight Ends Sports Bar & Grill",
        phone: "+14698506796",
        price: "$$",
        rating: 3,
        review_count: 244,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/tight-ends-sports-bar-and-grill-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "casanova-hookah-lounge-richardson",
        categories: [[Object]],
        coordinates: {
            latitude: 32.9766642535316,
            longitude: -96.7222210921899,
        },
        delivery_time: 38,
        display_phone: "(903) 413-9405",
        distance: 3191.6514727694353,
        id: "C5BIzaWnkaGkSUkJ2NeaHw",
        image_url:
            "https://s3-media1.fl.yelpcdn.com/bphoto/RG3wHfcxGO7m-WID7WhwoQ/o.jpg",
        is_closed: false,
        location: {
            address1: "2050 N Collins  Blvd",
            address2: "Ste 101",
            address3: "",
            city: "Richardson",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75080",
        },
        name: "Casanova Hookah Lounge",
        phone: "+19034139405",
        price: "$$",
        rating: 3.5,
        review_count: 93,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/casanova-hookah-lounge-richardson?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "grand-lux-cafe-dallas-dallas",
        categories: [[Object], [Object]],
        coordinates: { latitude: 32.930909, longitude: -96.8202009 },
        delivery_time: 38,
        display_phone: "(972) 385-3114",
        distance: 12581.631476854474,
        id: "odb6CNENavPGL7w4Cm4fxA",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/RlkeM-HQDVt3Pdg45rheow/o.jpg",
        is_closed: false,
        location: {
            address1: "13420 N Dallas Pkwy",
            address2: "",
            address3: "",
            city: "Dallas",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75240",
        },
        name: "Grand Lux Cafe - Dallas",
        phone: "+19723853114",
        price: "$$",
        rating: 3.5,
        review_count: 833,
        transactions: ["delivery", "restaurant_reservation"],
        url: "https://www.yelp.com/biz/grand-lux-cafe-dallas-dallas?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "lilys-cafe-plano",
        categories: [[Object], [Object], [Object]],
        coordinates: {
            latitude: 33.0405953292575,
            longitude: -96.7507037102425,
        },
        delivery_time: 38,
        display_phone: "(972) 312-9732",
        distance: 10131.568673276395,
        id: "TFmrYQuUDb8p6tf-6V-Vbw",
        image_url:
            "https://s3-media3.fl.yelpcdn.com/bphoto/zmxXSG8GtQIfs9J_mgYYuQ/o.jpg",
        is_closed: false,
        location: {
            address1: "3100 Independence Pkwy",
            address2: "Ste 299",
            address3: "",
            city: "Plano",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75075",
        },
        name: "Lily's Cafe",
        phone: "+19723129732",
        price: "$",
        rating: 4.5,
        review_count: 233,
        transactions: ["delivery", "pickup"],
        url: "https://www.yelp.com/biz/lilys-cafe-plano?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "pangea-restaurant-and-bar-garland",
        categories: [[Object], [Object]],
        coordinates: { latitude: 32.9723585647536, longitude: -96.65541570659 },
        delivery_time: 38,
        display_phone: "(214) 703-2222",
        distance: 3471.713480720235,
        id: "3PjHKPgOK6U8hA9F71w1vg",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/vgNQ_lEmLdsYrjDkqKC73Q/o.jpg",
        is_closed: false,
        location: {
            address1: "6309 N President George Bush Hwy",
            address2: "Ste 8101",
            address3: "",
            city: "Garland",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75044",
        },
        name: "Pangea Restaurant & Bar",
        phone: "+12147032222",
        price: "$$",
        rating: 4,
        review_count: 466,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/pangea-restaurant-and-bar-garland?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
    {
        alias: "desperados-mexican-restaurant-dos-garland-2",
        categories: [[Object], [Object]],
        coordinates: { latitude: 32.97388, longitude: -96.68143 },
        delivery_time: 38,
        display_phone: "(972) 530-8886",
        distance: 1430.1632995984633,
        id: "SucaNHf8fBKKiZ29aDSZvA",
        image_url:
            "https://s3-media4.fl.yelpcdn.com/bphoto/96R4JejN80j0T4w4JuIM0A/o.jpg",
        is_closed: false,
        location: {
            address1: "3443 W Campbell Rd",
            address2: "Ste 550",
            address3: "",
            city: "Garland",
            country: "US",
            display_address: [Array],
            state: "TX",
            zip_code: "75044",
        },
        name: "Desperados Mexican Restaurant Dos",
        phone: "+19725308886",
        price: "$$",
        rating: 4,
        review_count: 291,
        transactions: ["delivery"],
        url: "https://www.yelp.com/biz/desperados-mexican-restaurant-dos-garland-2?adjust_creative=S6uGhh9p1KCP0ZyBW3pHWw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=S6uGhh9p1KCP0ZyBW3pHWw",
    },
];
